<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
require __DIR__.'/bootstrap.php';require __DIR__.'/schedule.php';require __DIR__.'/services.php';
$command=$argv[1]??'help';
if($command==='init'){db()->exec(file_get_contents(__DIR__.'/schema.sql'));echo "Database initialized; no service records or default passwords inserted.\n";exit;}
if($command==='admin'){$p=phone(getenv('ADMIN_PHONE')?:'',true);$pw=getenv('ADMIN_PASSWORD')?:'';$name=getenv('ADMIN_NAME')?:'';if(strlen($pw)<14||strlen($pw)>128||count(preg_split('/\s+/u',trim($name)))<3){fwrite(STDERR,"Set ADMIN_PHONE, ADMIN_NAME (three parts), ADMIN_PASSWORD (14-128 characters).\n");exit(1);}if(query('SELECT id FROM users WHERE phone=?',[$p])->fetch()){fwrite(STDERR,"Account exists. Use promote to grant admin; password is not overwritten.\n");exit(1);}query("INSERT INTO users(phone,password_hash,full_name,role) VALUES(?,?,?,'admin')",[$p,password_hash($pw,PASSWORD_DEFAULT),trim($name)]);echo "Admin created.\n";exit;}
if($command==='promote'){$p=phone(getenv('ADMIN_PHONE')?:'',true);$s=query("UPDATE users SET role='admin' WHERE phone=?",[$p]);if(!$s->rowCount()){fwrite(STDERR,"Account not found.\n");exit(1);}echo "Admin role granted.\n";exit;}
if($command==='import'){
 $file=$argv[2]??'';if(!is_file($file)||filesize($file)>10485760){fwrite(STDERR,"Provide a JSON file smaller than 10MB.\n");exit(1);} $rows=json_decode(file_get_contents($file),true,64,JSON_THROW_ON_ERROR);if(!is_array($rows)||!array_is_list($rows)||count($rows)>10000){fwrite(STDERR,"Expected a list with at most 10000 records.\n");exit(1);} $commit=in_array('--commit',$argv,true);$count=0;db()->beginTransaction();try{foreach($rows as $row){if(!is_array($row))throw new RuntimeException('Invalid record');$url=text($row,'source_url',1000,true);if(!filter_var($url,FILTER_VALIDATE_URL)||!in_array(parse_url($url,PHP_URL_SCHEME),['https','http'],true))throw new RuntimeException('source_url required');$checked=text($row,'source_checked_at',40,true);$time=strtotime($checked);if(!$time||$time>time())throw new RuntimeException('Valid past source_checked_at required');$cat=query('SELECT id FROM categories WHERE slug=?',[text($row,'category_slug',60,true)])->fetch();if(!$cat)throw new RuntimeException('Unknown category_slug');$areaName=text($row,'area_name',100,true);$scope=$row['scope']??'city';if(!in_array($scope,['city','rural'],true))throw new RuntimeException('Invalid scope');query('INSERT OR IGNORE INTO areas(name,scope) VALUES(?,?)',[$areaName,$scope]);$area=query('SELECT id FROM areas WHERE name=?',[$areaName])->fetch();$name=text($row,'name',160,true);if(query('SELECT id FROM services WHERE name=? AND category_id=? AND area_id=?',[$name,$cat['id'],$area['id']])->fetch())continue;$row['category_id']=(int)$cat['id'];$row['area_id']=(int)$area['id'];$row['schedule']=[];$id=insertService($row,null,'pending');query('UPDATE services SET source_url=?,source_checked_at=? WHERE id=?',[$url,gmdate('c',$time),$id]);$count++;}if($commit)db()->commit();else db()->rollBack();}catch(Throwable $e){if(db()->inTransaction())db()->rollBack();throw $e;}echo ($commit?'Imported pending review: ':'Dry run, no records saved: ').$count."\n";exit;
}
echo "Commands:\n php server/console.php init\n php server/console.php admin\n php server/console.php promote\n php server/console.php import /path/services.json [--commit]\nNo automatic scraping, invented service data, or imported live availability. Review sources before approval.\n";
