<?php
declare(strict_types=1);
const SERVICE_SELECT='SELECT s.*,c.name category_name,c.slug category_slug,c.icon,c.color,c.kind,c.supports_duty,a.name area_name,a.scope FROM services s JOIN categories c ON c.id=s.category_id JOIN areas a ON a.id=s.area_id';
function serviceRow(int $id): array { $s=query(SERVICE_SELECT.' WHERE s.id=?',[$id])->fetch(); if(!$s) fail(404,'الخدمة غير موجودة'); return $s; }
function serviceOutput(array $s,bool $private=false): array { $s=array_merge($s,serviceStatus($s)); $s['details']=json_decode($s['details'],true)?:new stdClass(); $s['schedule']=json_decode($s['schedule'],true)?:[]; if(!$private) {unset($s['owner_id'],$s['rejection_reason']);} return $s; }
function mayEdit(array $s,array $u): void { if($u['role']!=='admin'&&(int)$s['owner_id']!==(int)$u['id']) fail(403,'لا يمكنك إدارة هذه الخدمة'); }
function servicePayload(array $v): array { $cat=(int)($v['category_id']??0); $area=(int)($v['area_id']??0); if(!query('SELECT id FROM categories WHERE id=?',[$cat])->fetch()||!query('SELECT id FROM areas WHERE id=?',[$area])->fetch()) fail(422,'اختر نوع الخدمة والمنطقة'); $details=$v['details']??[]; if(!is_array($details)||count($details)>20) fail(422,'تفاصيل غير صالحة'); foreach($details as $k=>$d) { if(!is_string($k)||strlen($k)>40||!is_string($d)||mb_strlen($d)>2000) fail(422,'تفاصيل غير صالحة'); } return ['name'=>text($v,'name',160,true),'category_id'=>$cat,'area_id'=>$area,'address'=>text($v,'address',500,true),'phone'=>phone(text($v,'phone',30)),'whatsapp'=>phone(text($v,'whatsapp',30)),'description'=>text($v,'description',4000),'details'=>json_encode((object)$details,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR),'schedule'=>json_encode(validateSchedule($v['schedule']??[]),JSON_THROW_ON_ERROR)]; }
function insertService(array $v,?int $owner,string $approval='pending'): int { $p=servicePayload($v); $p+=['owner_id'=>$owner,'approval'=>$approval,'created_at'=>now(),'updated_at'=>now()]; $keys=array_keys($p); query('INSERT INTO services('.implode(',',$keys).') VALUES('.implode(',',array_fill(0,count($p),'?')).')',array_values($p)); return (int)db()->lastInsertId(); }
function serviceRoute(string $path,string $method): void {
 if($path==='/meta'&&$method==='GET') respond(['categories'=>query('SELECT * FROM categories ORDER BY sort_order,id')->fetchAll(),'areas'=>query('SELECT * FROM areas ORDER BY name')->fetchAll()]);
 if($path==='/services'&&$method==='GET') { $where=["s.approval='approved'"]; $args=[]; foreach(['category'=>'c.slug','area'=>'s.area_id','scope'=>'a.scope'] as $key=>$col) if(!empty($_GET[$key])) {$where[]="$col=?";$args[]=(string)$_GET[$key];} if(!empty($_GET['q'])) {$where[]='(s.name LIKE ? OR s.address LIKE ? OR s.details LIKE ?)';$q='%'.mb_substr((string)$_GET['q'],0,100).'%';array_push($args,$q,$q,$q);} $rows=query(SERVICE_SELECT.' WHERE '.implode(' AND ',$where).' ORDER BY s.name',$args)->fetchAll(); $rows=array_map(fn($r)=>serviceOutput($r),$rows); if(!empty($_GET['status'])) $rows=array_values(array_filter($rows,fn($r)=>$_GET['status']==='duty'?$r['on_duty']:$r['status']===$_GET['status'])); $page=max(1,(int)($_GET['page']??1)); respond(['items'=>array_slice($rows,($page-1)*24,24),'total'=>count($rows),'page'=>$page]); }
 if($path==='/my/services'&&$method==='GET') { $u=requireUser(); respond(['items'=>array_map(fn($r)=>serviceOutput($r,true),query(SERVICE_SELECT.' WHERE owner_id=? ORDER BY s.id DESC',[$u['id']])->fetchAll())]); }
 if($path==='/services'&&$method==='POST') { $u=requireUser(); rateLimit('create:'.$u['id'],30,3600); $v=body(); $owner=(int)$u['id']; if($u['role']==='admin'&&array_key_exists('owner_id',$v)) {$owner=$v['owner_id']?(int)$v['owner_id']:null; if($owner&&!query('SELECT id FROM users WHERE id=?',[$owner])->fetch()) fail(422,'المالك غير موجود');} $id=insertService($v,$owner,$u['role']==='admin'?'approved':'pending'); audit('service.create',$id); respond(['service'=>serviceOutput(serviceRow($id),true)],201); }
 if(preg_match('#^/services/([0-9]+)(/availability)?$#',$path,$m)) { $id=(int)$m[1]; $s=serviceRow($id); if($method==='GET'&&empty($m[2])) { if($s['approval']!=='approved') mayEdit($s,requireUser()); respond(['service'=>serviceOutput($s)]); } $u=requireUser(); mayEdit($s,$u);
  if($method==='PATCH'&&!empty($m[2])) { if($s['approval']!=='approved') fail(409,'الخدمة لم تعتمد بعد'); $v=body(); $mode=$v['status']??'auto'; if(!in_array($mode,['auto','open','closed'],true)) fail(422,'حالة غير صالحة'); $hours=(int)($v['hours']??12); if($hours<1||$hours>24) fail(422,'مدة الحالة من 1 إلى 24 ساعة'); $duty=$v['on_duty']??false; if(!is_bool($duty)) fail(422,'حالة المناوبة غير صالحة'); if($duty&&!$s['supports_duty']) fail(422,'هذا النوع لا يدعم المناوبة'); $until=gmdate('c',time()+$hours*3600); query('UPDATE services SET override_status=?,override_until=?,duty_until=?,updated_at=? WHERE id=?',[$mode==='auto'?null:$mode,$mode==='auto'?null:$until,$duty?$until:null,now(),$id]); audit('service.availability',$id); respond(['service'=>serviceOutput(serviceRow($id),true)]); }
  if($method==='PATCH'&&empty($m[2])) { $v=body(); $p=servicePayload($v); if($u['role']!=='admin') { if((int)$p['category_id']!==(int)$s['category_id']) fail(403,'تغيير نوع الخدمة للمدير فقط'); $oldDetails=json_decode($s['details'],true)?:[]; $newDetails=json_decode($p['details'],true)?:[]; ksort($oldDetails);ksort($newDetails); if($p['name']!==$s['name']||$p['address']!==$s['address']||(int)$p['area_id']!==(int)$s['area_id']||$p['phone']!==$s['phone']||$p['whatsapp']!==$s['whatsapp']||$p['description']!==$s['description']||$oldDetails!==$newDetails) $p['approval']='pending'; } else { if(array_key_exists('owner_id',$v)) { $owner=$v['owner_id']?(int)$v['owner_id']:null; if($owner&&!query('SELECT id FROM users WHERE id=?',[$owner])->fetch()) fail(422,'المالك غير موجود'); $p['owner_id']=$owner; } } $p['updated_at']=now(); query('UPDATE services SET '.implode(',',array_map(fn($k)=>$k.'=?',array_keys($p))).' WHERE id=?',[...array_values($p),$id]); audit('service.update',$id); respond(['service'=>serviceOutput(serviceRow($id),true)]); }
  if($method==='DELETE'&&empty($m[2])) {requireUser(true);query('DELETE FROM services WHERE id=?',[$id]);audit('service.delete',$id);respond(['ok'=>true]);}
 }
 if(!str_starts_with($path,'/admin/')) return; requireUser(true);
 if($path==='/admin/users'&&$method==='GET') respond(['items'=>query('SELECT id,full_name,phone,role FROM users ORDER BY id DESC')->fetchAll()]);
 if($path==='/admin/services'&&$method==='GET') respond(['items'=>array_map(fn($r)=>serviceOutput($r,true),query(SERVICE_SELECT.' ORDER BY s.id DESC')->fetchAll())]);
 if(preg_match('#^/admin/services/([0-9]+)/review$#',$path,$m)&&$method==='POST') { $v=body(); $decision=$v['approval']??''; if(!in_array($decision,['approved','rejected'],true)) fail(422,'قرار غير صالح'); serviceRow((int)$m[1]); query('UPDATE services SET approval=?,rejection_reason=?,updated_at=? WHERE id=?',[$decision,text($v,'rejection_reason',500),now(),(int)$m[1]]);audit('service.'.$decision,(int)$m[1]);respond(['ok'=>true]); }
 if(preg_match('#^/admin/(categories|areas)(?:/([0-9]+))?$#',$path,$m)) { $table=$m[1]; $id=(int)($m[2]??0); if($id&&!query("SELECT id FROM $table WHERE id=?",[$id])->fetch()) fail(404,'السجل غير موجود'); if($method==='DELETE'&&$id) { $fk=$table==='areas'?'area_id':'category_id';if(query("SELECT id FROM services WHERE $fk=? LIMIT 1",[$id])->fetch()) fail(409,'انقل الخدمات المرتبطة قبل الحذف');query("DELETE FROM $table WHERE id=?",[$id]);audit($table.'.delete',$id);respond(['ok'=>true]); } if(in_array($method,['POST','PATCH'],true)) { $v=body();$p=['name'=>text($v,'name',100,true)]; if($table==='areas') {$scope=$v['scope']??'city';if(!in_array($scope,['city','rural'],true))fail(422,'نطاق غير صالح');$p['scope']=$scope;} else { $slug=text($v,'slug',60,true);if(!preg_match('/^[a-z][a-z0-9-]*$/D',$slug))fail(422,'الرابط يجب أن يكون حروفًا إنكليزية صغيرة');$icon=text($v,'icon',30,true);if(!in_array($icon,['pill','stethoscope','fuel','bus','building','wrench','shopping','heart'],true))fail(422,'أيقونة غير صالحة');$color=text($v,'color',7,true);if(!preg_match('/^#[0-9a-fA-F]{6}$/D',$color))fail(422,'لون غير صالح');$layout=$v['layout']??'cards';$kind=$v['kind']??'general';if(!in_array($layout,['cards','list'],true)||!in_array($kind,['general','pharmacy','doctor','station','transport'],true))fail(422,'إعداد غير صالح');$p+=['slug'=>$slug,'icon'=>$icon,'color'=>$color,'layout'=>$layout,'kind'=>$kind,'supports_duty'=>!empty($v['supports_duty'])?1:0,'sort_order'=>(int)($v['sort_order']??0)]; } try { if($id)query("UPDATE $table SET ".implode(',',array_map(fn($k)=>$k.'=?',array_keys($p))).' WHERE id=?',[...array_values($p),$id]);else {query("INSERT INTO $table (".implode(',',array_keys($p)).') VALUES('.implode(',',array_fill(0,count($p),'?')).')',array_values($p));$id=(int)db()->lastInsertId();} } catch(PDOException $e) {if($e->getCode()==='23000')fail(409,'الاسم أو الرابط مستخدم بالفعل');throw $e;}audit($table.'.save',$id);respond(['ok'=>true,'id'=>$id]); } }
}
