import { FormEvent,useState } from 'react';
import { Meta,Service,ServiceInput,User,detailLabels } from '../types';
import { api,errorText } from '../api';
import ScheduleEditor from './ScheduleEditor';
export default function ServiceForm({meta,initial,onSaved,onCancel,users}:{meta:Meta;initial?:Service;onSaved:()=>void;onCancel?:()=>void;users?:User[]}) {
 const [v,setV]=useState<ServiceInput>(initial?{name:initial.name,category_id:initial.category_id,area_id:initial.area_id,address:initial.address,phone:initial.phone,whatsapp:initial.whatsapp,description:initial.description,details:initial.details,schedule:initial.schedule,owner_id:initial.owner_id}:{name:'',category_id:meta.categories[0]?.id||0,area_id:0,address:'',phone:'',whatsapp:'',description:'',details:{},schedule:[],...(users?{owner_id:null}:{})});
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');const category=meta.categories.find(c=>c.id===v.category_id);const keys=category?.kind==='doctor'?['specialty']:category?.kind==='station'?['gasoline','diesel','electric']:category?.kind==='transport'?['vehicle','stops','fare','frequency']:[];
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await api(initial?`/services/${initial.id}`:'/services',initial?'PATCH':'POST',v);onSaved();}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 return <form className="card form-card" onSubmit={submit}><h2>{initial?'تعديل الخدمة':'إضافة خدمة جديدة'}</h2><p className="muted">أدخل معلومات صحيحة. طلبات المستخدمين لا تظهر للعامة إلا بعد مراجعة المدير.</p>{error&&<p className="error" role="alert">{error}</p>}<div className="form-grid"><label>اسم الخدمة<input required maxLength={160} value={v.name} onChange={e=>setV({...v,name:e.target.value})}/></label><label>نوع الخدمة<select required value={v.category_id} disabled={!!initial&&!users} onChange={e=>setV({...v,category_id:Number(e.target.value),details:{}})}>{meta.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>المنطقة<select required value={v.area_id||''} onChange={e=>setV({...v,area_id:Number(e.target.value)})}><option value="">اختر المنطقة</option>{meta.areas.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>العنوان التفصيلي<input required maxLength={500} value={v.address} onChange={e=>setV({...v,address:e.target.value})}/></label><label>رقم الاتصال<input type="tel" dir="ltr" placeholder="+963…" maxLength={30} value={v.phone} onChange={e=>setV({...v,phone:e.target.value})}/></label><label>رقم واتساب<input type="tel" dir="ltr" placeholder="+963…" maxLength={30} value={v.whatsapp} onChange={e=>setV({...v,whatsapp:e.target.value})}/></label>{users&&<label>ربط بحساب مستخدم<select value={v.owner_id||''} onChange={e=>setV({...v,owner_id:e.target.value?Number(e.target.value):null})}><option value="">بدون مالك</option>{users.map(u=><option key={u.id} value={u.id}>{u.full_name} — {u.phone}</option>)}</select></label>}</div><label>وصف الخدمة<textarea rows={3} maxLength={4000} value={v.description} onChange={e=>setV({...v,description:e.target.value})}/></label><div className="form-grid">{keys.map(key=><label key={key}>{detailLabels[key]}{['gasoline','diesel','electric','vehicle'].includes(key)?<select value={v.details[key]||''} onChange={e=>setV({...v,details:{...v.details,[key]:e.target.value}})}><option value="">غير محدد</option>{(key==='vehicle'?['باص','سرفيس']:['يوجد','لا يوجد']).map(x=><option key={x}>{x}</option>)}</select>:<textarea rows={key==='stops'?4:1} maxLength={2000} value={v.details[key]||''} onChange={e=>setV({...v,details:{...v.details,[key]:e.target.value}})}/>}</label>)}</div><ScheduleEditor value={v.schedule} onChange={schedule=>setV({...v,schedule})}/>{!meta.areas.length&&<p className="notice">يجب أن يضيف المدير منطقة واحدة على الأقل قبل استقبال الطلبات.</p>}<div className="actions"><button className="primary" disabled={busy||!meta.areas.length}>{busy?'جارٍ الحفظ…':'حفظ الخدمة'}</button>{onCancel&&<button className="secondary" type="button" onClick={onCancel}>إلغاء</button>}</div></form>;
}
